/* 
 * File:   W25QXXXF_hwprofile.h
 * Author: deepak_dogra, modified by Maniruzzaman
 *
 * Created on 12 February, 2016, 12:10 PM
 */

#ifndef W25QXXXF_HWPROFILE_H
#define	W25QXXXF_HWPROFILE_H

#include "../hardware/bsp.h"

#ifdef	__cplusplus
extern "C" {
#endif
/**************************************************************************/
    /* Hardware Profile Handlers                                              */
    /**************************************************************************/
    #define W25QXXXF_SS_TRIS        TRIS_REG_BIT(W25QXXXF_SS_PORT,W25QXXXF_SS_PIN)
    #define W25QXXXF_SS_WRITE       LAT_REG_BIT(W25QXXXF_SS_PORT,W25QXXXF_SS_PIN)
    #define W25QXXXF_SS_READ        PORT_REG_BIT(W25QXXXF_SS_PORT,W25QXXXF_SS_PIN)
    #define W25QXXXF_SS_PULLUP      CNPU_REG_BIT(W25QXXXF_SS_PORT,W25QXXXF_SS_PIN)
    #define W25QXXXF_SS_PULLDN      CNPD_REG_BIT(W25QXXXF_SS_PORT,W25QXXXF_SS_PIN)

    #define W25QXXXF_RESET_TRIS     TRIS_REG_BIT(W25QXXXF_RESET_PORT,W25QXXXF_RESET_PIN)
    #define W25QXXXF_RESET_WRITE    LAT_REG_BIT(W25QXXXF_RESET_PORT,W25QXXXF_RESET_PIN)
    #define W25QXXXF_RESET_READ     PORT_REG_BIT(W25QXXXF_RESET_PORT,W25QXXXF_RESET_PIN)
    #define W25QXXXF_RESET_PULLUP   CNPU_REG_BIT(W25QXXXF_RESET_PORT,W25QXXXF_RESET_PIN)
    #define W25QXXXF_RESET_PULLDN   CNPD_REG_BIT(W25QXXXF_RESET_PORT,W25QXXXF_RESET_PIN)

    #define W25QXXXF_SCK_TRIS       TRIS_REG_BIT(W25QXXXF_SCK_PORT,W25QXXXF_SCK_PIN)
    #define W25QXXXF_SCK_WRITE      LAT_REG_BIT(W25QXXXF_SCK_PORT,W25QXXXF_SCK_PIN)
    #define W25QXXXF_SCK_READ       PORT_REG_BIT(W25QXXXF_SCK_PORT,W25QXXXF_SCK_PIN)
    #define W25QXXXF_SCK_PULLUP     CNPU_REG_BIT(W25QXXXF_SCK_PORT,W25QXXXF_SCK_PIN)
    #define W25QXXXF_SCK_PULLDN     CNPD_REG_BIT(W25QXXXF_SCK_PORT,W25QXXXF_SCK_PIN)

    #define W25QXXXF_SDO_TRIS       TRIS_REG_BIT(W25QXXXF_SDO_PORT,W25QXXXF_SDO_PIN)
    #define W25QXXXF_SDO_WRITE      LAT_REG_BIT(W25QXXXF_SDO_PORT,W25QXXXF_SDO_PIN)
    #define W25QXXXF_SDO_READ       PORT_REG_BIT(W25QXXXF_SDO_PORT,W25QXXXF_SDO_PIN)
    #define W25QXXXF_SDO_PULLUP     CNPU_REG_BIT(W25QXXXF_SDO_PORT,W25QXXXF_SDO_PIN)
    #define W25QXXXF_SDO_PULLDN     CNPD_REG_BIT(W25QXXXF_SDO_PORT,W25QXXXF_SDO_PIN)

    #define W25QXXXF_SDI_TRIS       TRIS_REG_BIT(W25QXXXF_SDI_PORT,W25QXXXF_SDI_PIN)
    #define W25QXXXF_SDI_WRITE      LAT_REG_BIT(W25QXXXF_SDI_PORT,W25QXXXF_SDI_PIN)
    #define W25QXXXF_SDI_READ       PORT_REG_BIT(W25QXXXF_SDI_PORT,W25QXXXF_SDI_PIN)
    #define W25QXXXF_SDI_PULLUP     CNPU_REG_BIT(W25QXXXF_SDI_PORT,W25QXXXF_SDI_PIN)
    #define W25QXXXF_SDI_PULLDN     CNPD_REG_BIT(W25QXXXF_SDI_PORT,W25QXXXF_SDI_PIN)


    #define W25QXXXF_WP_TRIS       TRIS_REG_BIT(W25QXXXF_WP_PORT,W25QXXXF_WP_PIN)
    #define W25QXXXF_WP_WRITE      LAT_REG_BIT(W25QXXXF_WP_PORT,W25QXXXF_WP_PIN) 
    #define W25QXXXF_WP_READ       PORT_REG_BIT(W25QXXXF_WP_PORT,W25QXXXF_WP_PIN)    
    #define W25QXXXF_WP_PULLUP     CNPU_REG_BIT(W25QXXXF_WP_PORT,W25QXXXF_WP_PIN)
    #define W25QXXXF_WP_PULLDN     CNPD_REG_BIT(W25QXXXF_WP_PORT,W25QXXXF_WP_PIN)
#ifdef EXTRA_PIN_MODE 
    #define W25QXXXF_HOLD_TRIS     TRIS_REG_BIT(W25QXXXF_HOLD_PORT,W25QXXXF_HOLD_PIN)
    #define W25QXXXF_HOLD_WRITE    LAT_REG_BIT(W25QXXXF_HOLD_PORT,W25QXXXF_HOLD_PIN)
    #define W25QXXXF_HOLD_READ     PORT_REG_BIT(W25QXXXF_HOLD_PORT,W25QXXXF_HOLD_PIN)
    #define W25QXXXF_HOLD_PULLUP   CNPU_REG_BIT(W25QXXXF_HOLD_PORT,W25QXXXF_HOLD_PIN)
    #define W25QXXXF_HOLD_PULLDN   CNPD_REG_BIT(W25QXXXF_HOLD_PORT,W25QXXXF_HOLD_PIN)
#endif    
#ifdef	__cplusplus
}
#endif

#endif	/* W25QXXXF_HWPROFILE_H */

