/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

/* 
 * File:   
 * Author: 
 * Comments:
 * Revision history: 
 */

// This is a guard condition so that contents of this file are not included
// more than once.  
#ifndef _QUECTEL_HW_PROFILE_H
#define	_QUECTEL_HW_PROFILE_H

#include "../hardware/bsp.h" 

#ifdef	__cplusplus
extern "C" {
#endif
    
    #define QUECTEL_RESET_TRIS        TRIS_REG_BIT(QUECTEL_RESET_PORT,QUECTEL_RESET_PIN)
    #define QUECTEL_RESET_WRITE       LAT_REG_BIT(QUECTEL_RESET_PORT,QUECTEL_RESET_PIN)
    #define QUECTEL_RESET_READ        PORT_REG_BIT(QUECTEL_RESET_PORT,QUECTEL_RESET_PIN)
    #define QUECTEL_RESET_PULLUP      CNPU_REG_BIT(QUECTEL_RESET_PORT,QUECTEL_RESET_PIN)
    #define QUECTEL_RESET_PULLDN      CNPD_REG_BIT(QUECTEL_RESET_PORT,QUECTEL_RESET_PIN)    
    
    
#ifdef	__cplusplus
}
#endif    


#endif	/* _QUECTEL_HW_PROFILE_H */

